automation:
  url: http://cobranza.qa.urupago.com.uy/#/login
  drivers:
    chrome:
      driver-path: //home/graviel/Descargas/intelij/chromedriver
    firefox:
      driver-path: //home/graviel/Descargas/intelij/gecko/geckodriver
    remote:
      driver-path: s
spring:
  profiles:
    active: chrome
